Repository openziti/zrok, pull requests merged in 2025-04, with the labels that each got.

#923 add linux package - zrok-agent
  .github/workflows/promote-downstreams.yml
  .github/workflows/release.yml
  .goreleaser-linux-amd64.yml
  .goreleaser-linux-arm64.yml
  .goreleaser-linux-armel.yml
  .goreleaser-linux-armhf.yml
  CHANGELOG.md
  docs/guides/_linux-agent-install.mdx
  docs/guides/agent/_category_.json
  docs/guides/agent/index.mdx
  docs/guides/agent/linux-service.mdx
  docs/guides/agent/windows-service/index.mdx
  docs/guides/linux-user-share/_category_.json
  docs/guides/linux-user-share/index.mdx
  nfpm/zrok-agent.service
  nfpm/zrok-share@.service
Labels: documentation, feature

#929 Persist Private Accesses and Reserved Shares in Agent
  CHANGELOG.md
  agent/access.go
  agent/accessPrivate.go
  agent/agent.go
  agent/registry.go
  agent/releaseAccess.go
  agent/releaseShare.go
  agent/share.go
  agent/sharePrivate.go
  agent/sharePublic.go
  agent/shareReserved.go
  environment/env_core/model.go
  environment/env_v0_3/api.go
  environment/env_v0_4/api.go
  environment/env_v0_4/dirs.go
Labels: feature

#934 UI Tweaks
  CHANGELOG.md
  controller/config/config.go
  controller/configuration.go
  etc/ctrl.yml
  rest_model_zrok/configuration.go
  rest_server_zrok/embedded_spec.go
  sdk/nodejs/sdk/src/api/models/ModelConfiguration.ts
  sdk/python/src/docs/Configuration.md
  sdk/python/src/test/test_configuration.py
  sdk/python/src/zrok_api/models/configuration.py
  specs/zrok.yml
  ui/src/Login.tsx
  ui/src/ReleaseAccessModal.tsx
  ui/src/ReleaseEnvironmentModal.tsx
  ui/src/ReleaseShareModal.tsx
  ui/src/api/models/ModelConfiguration.ts
Labels: enhancement

#937 Auto-rebase
  CHANGELOG.md
  environment/env_v0_4/root.go
Labels: feature

#946 Unbootstrapper; Canary Additions
  .gitignore
  CHANGELOG.md
  canary/config.go
  canary/dangerous.go
  canary/disabler.go
  canary/enabler.go
  canary/metrics.go
  cmd/zrok/adminUnbootstrap.go
  cmd/zrok/testCanaryEnabler.go
  controller/unbootstrap.go
  sdk/golang/sdk/environment.go
  sdk/golang/sdk/model.go
Labels: spike, feature

#952 zrok agent console Improvements
  CHANGELOG.md
  cmd/zrok/agentConsole.go
Labels: enhancement, feature
